{% set name = "mdbenchmark" %}
{% set version = "2.0.1b2" %}
{% set sha256 = "31ed2d3962f82f672abcbb813bea0ebd8c30ef3fdcd7e47384656db3c261c4e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mdbenchmark/mdbenchmark-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed -vv .
  skip: true  # [win]
  entry_points:
    - mdbenchmark = mdbenchmark.cli:cli

requirements:
  host:
    - python
    - poetry
    - pip
  run:
    - python
    - numpy >=1.8
    - datreant >=1.0.0
    - click >=6.7
    - jinja2
    - pandas
    - matplotlib >=2
    - xdg <2  # [py2k]
    - xdg >=2  # [py>=35]
    - python-levenshtein
    - tabulate >=0.8.2

test:
  requires:
    - libglu  # [linux]
  imports:
    - mdbenchmark
  commands:
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" mdbenchmark  # [linux]
    - mdbenchmark  # [not linux]

about:
  home: https://github.com/bio-phys/MDBenchmark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Benchmark molecular dynamics simulations'

extra:
  recipe-maintainers:
    - kain88-de
    - mimischi
