{% set name = "mdbenchmark" %}
{% set version = "1.3.3" %}
{% set sha256 = "0cdbd36e0deacae86df212ed7122abc770d356458c17509b9252e0722a741d1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win]
  entry_points:
    - mdbenchmark = mdbenchmark.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.8
    - mdsynthesis
    - click
    - jinja2
    - pandas
    - matplotlib
    - xdg <2
    - python-levenshtein

test:
  imports:
    - mdbenchmark
  commands:
    - mdbenchmark

about:
  home: https://github.com/bio-phys/MDBenchmark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Benchmark molecular dynamics simulations'

extra:
  recipe-maintainers:
    - kain88-de
    - mimischi
