{% set version = "3.0.1" %}
{% set sha256 = "3b2ebb693737a93155a67a7f25f3f5d20140ba8d87e5bda461e44840d0f1f87d" %}

package:
  name: mdbenchmark
  version: {{ version }}

source:
  fn: mdbenchmark-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mdbenchmark/mdbenchmark-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  skip: true  # [win]
  entry_points:
    - mdbenchmark = mdbenchmark.cli:cli

requirements:
  host:
    - python
    - poetry
    - pip
  run:
    - python
    - numpy >=1.8
    - datreant >=1.0.0
    - click >=6.7
    - jinja2
    - pandas
    - matplotlib-base >=2
    - xdg <2  # [py2k]
    - xdg >=2  # [py>=35]
    - python-levenshtein
    - tabulate >=0.8.2

test:
  requires:
    - libglu  # [linux]
  imports:
    - mdbenchmark
  commands:
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" mdbenchmark  # [linux]
    - mdbenchmark  # [not linux]

about:
  home: https://github.com/bio-phys/MDBenchmark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Quickly generate, start and analyze benchmarks for your molecular dynamics simulations.
  doc_url: https://docs.mdbenchmark.org
  dev_url: https://github.com/bio-phys/MDBenchmark
  description: >
    MDBenchmark is a tool to squeeze the maximum out of your limited computing resources. It tries to make it as easy as possible to set up systems on varying numbers of nodes and compare their performances to each other.

    You can also create a plot to get a quick overview of the possible performance (and show of to your friends)! The plot below shows the performance of an molecular dynamics system on up to five nodes with and without GPUs.

extra:
  recipe-maintainers:
    - kain88-de
    - mimischi
