{% set name = "mdbenchmark" %}
{% set version = "2.0.0" %}
{% set sha256 = "0749478d52d7651b7c9b05c4494431125e247531adfd38181b815e347e155558" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win]
  entry_points:
    - mdbenchmark = mdbenchmark.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.8
    - datreant >=1.0.0
    - click==6.7
    - jinja2
    - pandas
    - matplotlib <3.0
    - xdg <2
    - python-levenshtein
    - tabulate >=0.8.2

test:
  imports:
    - mdbenchmark
  commands:
    - mdbenchmark

about:
  home: https://github.com/bio-phys/MDBenchmark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Benchmark molecular dynamics simulations'

extra:
  recipe-maintainers:
    - kain88-de
    - mimischi
