{% set name = "mdbenchmark" %}
{% set version = "1.1.1" %}
{% set sha256 = "19b50a186ed63f37f03a1b926b8e4ce3acf14dd53a297946660d172020cb6b3e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win or py3k]
  entry_points:
    - mdbenchmark = mdbenchmark.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.8
    - mdsynthesis
    - click
    - jinja2
    - pandas
    - matplotlib
    - xdg <2
    - python-levenshtein

test:
  imports:
    - mdbenchmark
  commands:
    - mdbenchmark

about:
  home: https://github.com/bio-phys/MDBenchmark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Benchmark GROMACS simulations'

extra:
  recipe-maintainers:
    - kain88-de
