{% set name = "mdbenchmark" %}
{% set version = "2.0.0" %}
{% set sha256 = "0749478d52d7651b7c9b05c4494431125e247531adfd38181b815e347e155558" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed -vv .
  skip: true  # [win]
  entry_points:
    - mdbenchmark = mdbenchmark.cli:cli

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy >=1.8
    - datreant >=1.0.0
    - click==6.7       # [py<=36]
    # unpin for py37
    - click>=6.7       # [py>=37]   
    - jinja2
    - pandas
    - matplotlib <3.0  # [py27]
    - matplotlib       # [py>=34]
    - xdg <2           
    - python-levenshtein
    - tabulate >=0.8.2

test:
  requires:
    - libglu  # [linux]
  imports:
    - mdbenchmark
  commands:
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" mdbenchmark  # [linux]
    - mdbenchmark  # [not linux]

about:
  home: https://github.com/bio-phys/MDBenchmark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Benchmark molecular dynamics simulations'

extra:
  recipe-maintainers:
    - kain88-de
    - mimischi
