travis:
  secure:
    BINSTAR_TOKEN: B+euGCdaxVhIyBnQpAA8AZEt/+1CQDioxY0jnKoREhaSdCBYvMDTyXDYM1WAEn2j42+HV6s992d+GEg0agD44X9ahWAcqkh9a1BkEPkBpOv6W2lq0m3NrC/T0mBUfheVSj1Td4BTywZgzuByhhI06XMhYDF+mWP0+F8yZyObMILHvLdwX5hleYum5Xrk/ZQDnTsyqEUmMha5myunLQxBIThneMLs4P7fokwfDpuIWb67opt0atTwzfRF/NmfrRkBi6rWsljv/a3aALpwLDd/GARmHNuef6pVbpEoAW66PDeo7noLubfg4afSFNyuIUR2lpV+O9valZgtNmnPGu0sN5pGq7y9sinNLw/UGUQUElk2pDsODQivHmT0T2kBajNwyHEpN/DshYXwED1kVWrJ2A/HEOSwIXVwVILb7yP8xd3jeDGz/vOVu5FCbQN2cP2piOHGdVU3rCsQHd00H5Do+iRzNPc5n+/yL2qsIpdFCHX3ITGW2Iw65uxRBAdDd5XzTcpp8giECPceM3FcMyL5dOBFodSzdZXZzz0GJp2uur8ePyyYoyQki1QCFg6julIqR/hU4A+qCicssnpo+SiXF524blLDvzv/ZfVr/Vgk4w9Lfe1oDNc7GcOSEXrwaxnc70KbCaUVMjzBuT444LiMy70gDN1b70sHhIGJCg30pZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
