travis:
  secure:
    BINSTAR_TOKEN: CB/BL66ZbTysoPnbbAPhSXyjds9zVO4Quhgzy4/oIyMSN8Gftu30YDxiWy86Wvk1bfjWngrKhs1Ozj6kmb0IAUWvkELzt0F778RuR3S5gf5oIq3C7D/4q0L1JaHD7hhzkW7aVUdHiBwW74MMC4dOBchRR72EuJWPl5MI/qVFb+Dx6a0enPusIv1k+7ISR2p3Ch9M6hqbxEOhU8lsuPwTOPlMdys0kYLzKjuz8ISvDRQUwz4CiyxPFmQGJ5SV8r3OyfIgkiPdzcqplnpJa6P0iHT4fYSSoKpB/O4OyrmBqosJAorQdpchEfr8uipuoa1wwnoOz0jg+CR0IGENQYPUW7/NhTYGU1Yd9XjdjxQX0XJ+YP4jAggTH49X0CZS2rO/YQTHSgscxWXlP+Ly/U9tK0C9gbZM06C6HsTZOoJHAkkvw8OUtGMhFxfDQ/jzVmhmPRCZt0Ago0R6ou23TSzepJk9YYd7aqGJKBn6Om0J7Pw1tueUWdXZShihdKXNjLLngvLN0MGuh6selvFBtRq+NyvnSSmBj+SJmhW7dk88rvjEpY8wR3d/zdEKMQSlpbgYox7tulnaGW9mEUIbgO/QEThLJY+o9PsrJhHj07VlaQJKLqxuFkRP2hpMrTQeYW22IVMiw45HuFxSgAZdNJOGOqdz3XhLma7Xzvfb0XvRGf0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
