travis:
  secure:
    BINSTAR_TOKEN: j2o1W1TG+jsaTH+n3Ahh/Z+mGMOJXgIL70nFpDa0DP9HaNwUfuncctXISWKe2iA2nOQX9wtKg+kBmDaZOVOzqzGt/ZukBLe2PAN1LKIqSSZw/2kyHmSJ0bJt8Ehp0L+sNzjRiA1DV4PP6p1K6PffwdNy6EObtg8KmceRGbfr50GZfMmndpuwOtYrTsRjyzx+bt2fFg328oG8RaOo3lai5gZypMSk4cQTuDvt33BGGWL+vA2FMwKFamUbwaNT3jbnSWKJn/7icYqEm0RpgWbQQO1N6eFgiOaVbG9hhSw+5ygzvhgdSxnzwYeLhm9NlbPE13OJAwO8P1HYm4vQBi2kB7ATqJNB7dHlxEKa2MIiPafAdJFFCn3nTUlWeEzydJFHT6biedtHwMxN9wrJqnGY2KBcnm/7zwBK/x2ckSXPE9E0vt3A8DeUkYP9dF7j/StVCVQfeTFUHDqBrlc7abY8iZgVeCuSld95cwFruV0W289tfE/YWIZEQOewa2opFBc42hxFSVZHXQIuPkuq+VhUcBsKuMeHvZqNPMs95e3JjDwBhtRRkpy3K0qyaYMEae977lkAqFtGylT+GUy/bO2IuG/67pbqer/g8hDDUfeabv/KWqlHkq7NXYVnlb7GO5cM1ZSHa2SBkYl3mnGcTJC7Run3EQbG8iFwcWla2WWQFAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
